apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::659931264778:role/eks-node-role
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - userarn: arn:aws:iam::659931264778:user/goap-user
      username: goap-user
      groups:
        - system:masters  
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
